name = "TableCellCounts"
uuid = "35cd6abc-3ecd-48c1-9a2e-0f6a1285d9d9"
authors = ["Dilum Aluthge", "Brown Center for Biomedical Informatics", "contributors"]
version = "1.0.0-DEV"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ScientificTypes = "321657f4-b219-11e9-178b-2701a2544e81"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
DataFrames = "1"
ScientificTypes = "2, 3"
StatsBase = "0.33"
Tables = "1"
TypedTables = "1"
julia = "1.6"

[extras]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"

[targets]
test = ["CategoricalArrays", "DataFrames", "Test", "TypedTables"]
